### PR TITLE
Add Documentation to all functions

### PR DESCRIPTION
**Pull request by luii**
Enabled strict mode, add documentation and updated string interpolation to es6 template strings

### CODE REVIEW

**Comment by lite20** [comment]
Thumbs up from me

**Comment by piranna** [comment]
There are some typos on the text and I would try to stick to 80 columns, could you be able to fix them? Besides that it's an awesome work :-)

**Comment by luii** [comment]
Sure i will fix them, where are the typos

**Comment by piranna** [comment]
Over all the text. If you give me permissions on your repo I could be able to fix them.

**Comment by luii** [comment]
Addy you as collaborator. Sinne englisch is Not my native language this is very helpful

**Comment by piranna** [comment]
> Added you as collaborator. Sinne englisch is Not my native language this is very helpful

Done :-) Do you want to review it, or we merge it directly?

**Comment by luii** [comment]
You can merge it directly

**Comment by piranna** [comment]
Merged. Maybe we could add some tests here, too? :-)

**Comment by luii** [comment]
Im on it :D

**Comment by piranna** [comment]
Cool! :-D

**Pull request merged**
